### ISSUE TITLE
No module named 'timm'

### ISSUE THREAD

**Issue by xinguo2** [facebookresearch/MaskFormer#19]
When I run the demo.py，it happened:

Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    from mask_former import add_mask_former_config
  File "/root/MaskFormer-master/MaskFormer-master/demo/../mask_former/__init__.py", line 3, in <module>
    from . import modeling
  File "/root/MaskFormer-master/MaskFormer-master/demo/../mask_former/modeling/__init__.py", line 2, in <module>
    from .backbone.swin import D2SwinTransformer
  File "/root/MaskFormer-master/MaskFormer-master/demo/../mask_former/modeling/backbone/swin.py", line 16, in <module>
    from timm.models.layers import DropPath, to_2tuple, trunc_normal_
ModuleNotFoundError: No module named 'timm'

can you tell me why?

**Comment by bowenc0221** [comment]
Please follow [installation instructions](https://github.com/facebookresearch/MaskFormer/blob/master/INSTALL.md) to install required packages: `pip install -r requirements.txt`
