### ISSUE TITLE
Failed to download https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/torchvision/R-50.pkl

### ISSUE THREAD

**Issue by xinguo2** [facebookresearch/MaskFormer#21]
When I run python train_net.py --config-file configs/ade20k-full-847/maskformer_R50_bs16_200k.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0001, it happened:

 [Checkpointer] Loading from detectron2://ImageNetPretrained/torchvision/R-50.pkl ...
R-50.pkl: 0.00B [00:00, ?B/s]
Failed to download https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/torchvision/R-50.pkl
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/conda/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/conda/lib/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/opt/conda/lib/python3.7/http/client.py", line 942, in connect
    self._tunnel()
  File "/opt/conda/lib/python3.7/http/client.py", line 921, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

what can I do?
 If I download R50-pkl from the url  manually, which path should I put it under and what configs should to set?

**Comment by bowenc0221** [comment]
You can set `MODEL.WEIGHTS` to the path of pre-trained model weights on your disk.
