### ISSUE TITLE
errors occurred when running demo.py

### ISSUE THREAD

**Issue by fjremnav** [facebookresearch/MaskFormer#37]
When I run demo.py using the following command:
python ./demo/demo.py --config-file configs/cityscapes-19/maskformer_R101_bs16_90k.yaml --input ../videos/sanjose_street/test01000.png  --opts MODEL.WEIGHTS ./model_final_38c00c.pkl

It gives me the following errors:

[09/29 23:17:36 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/cityscapes-19/maskformer_R101_bs16_90k.yaml', input=['../videos/sanjose_street/test01000.png'], opts=['MODEL.WEIGHTS', './model_final_38c00c.pkl'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "./demo/demo.py", line 106, in <module>
    cfg = setup_cfg(args)
  File "./demo/demo.py", line 38, in setup_cfg
    add_mask_former_config(cfg)
  File "/home/user/4TB/fc_tmp/git/MaskFormer/demo/../mask_former/config.py", line 79, in add_mask_former_config
    cfg.MODEL.SWIN.QK_SCALE = None
  File "/home/henry.jeng/anaconda3/envs/remnav/lib/python3.7/site-packages/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/home/henry.jeng/anaconda3/envs/remnav/lib/python3.7/site-packages/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/home/henry.jeng/anaconda3/envs/remnav/lib/python3.7/site-packages/yacs/config.py", line 525, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'str'>, <class 'int'>, <class 'bool'>, <class 'tuple'>, <class 'list'>, <class 'float'>}

**Comment by bowenc0221** [comment]
Looks like you had the same issue with #20 (which I cannot reproduce on my side). The solution is to change `cfg.MODEL.SWIN.QK_SCALE = False` in https://github.com/facebookresearch/MaskFormer/blob/232bd1bc1c8929565c098c1002ebc8d21fa0f530/mask_former/config.py#L79

**Comment by fjremnav** [comment]
After changing None to False, demo.py is running OK
I am planning to measure inferencing speed on AGX platform and need to convert pth to onnx and then to tensorrt.
Do you have an experience of converting your trained pytorch  model to onnx format?

Thanks,
FC

**Comment by bowenc0221** [comment]
Sorry, I don't have any experience on that. You may want to check detectron2 document.

**Comment by mihaibujanca** [comment]
@fjremnav any luck with getting it working with tensorrt?
